# Generated by Django 3.0.8 on 2020-07-05 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20200705_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ManyToManyField(related_name='users_like', to='posts.Post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ManyToManyField(related_name='posts_like', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
